### ISSUE TITLE
relocations not resolved correctly.

### ISSUE THREAD

**Issue by ghost** [not-wlan/drvmap#6] opened 2018-10-27 00:18 UTC
https://media.discordapp.net/attachments/505117783802249226/505529605562564638/unknown.png?width=1493&height=576
As you can see, eax should hold a relocated address, but it doesn't.
Relocating before mapping the image seems to fix the problem.
(For whatever reason, if I don't do this, i'll get ``no relocations but flag isn't set. weird.``)

**Comment by not-wlan** [comment] 2018-11-05 13:04
I can't reproduce this at the moment since I don't have a driver that has relocations. Feel free to submit a PR if you figure it out.

**Comment by not-wlan** [comment] 2019-06-23 21:20
Should be fixed by 
https://github.com/not-wlan/drvmap/pull/10

**Closed by not-wlan** 2019-06-23 21:20 UTC

**Comment by ShoaShekelbergstein** [comment] 2019-06-23 22:53
@not-wlan Sorry, no. Actually fixing relocations is a bit more complex than #10, which only fixes the 'no relocations but flag isn't set' warning. I may look into this later if I've got time.
